export const currencyZones = [
  // Current
  { name: "Afghanistan", mapCode: "AF", currencyCode: "AFN" },
  { name: "Albania", mapCode: "AL", currencyCode: "ALL" },
  { name: "Algeria", mapCode: "DZ", currencyCode: "DZD" },
  { name: "Andorra", mapCode: "AD", currencyCode: "EUR" },
  { name: "Angola", mapCode: "AO", currencyCode: "AOA" },
  { name: "Argentina", mapCode: "AR", currencyCode: "ARS" },
  { name: "Armenia", mapCode: "AM", currencyCode: "AMD" },
  { name: "Australia", mapCode: "AU", currencyCode: "AUD" },
  { name: "Azerbaijan", mapCode: "AZ", currencyCode: "AZN" },
  { name: "Bahamas", mapCode: "BS", currencyCode: "BSD" },
  { name: "Bahrain", mapCode: "BH", currencyCode: "BHD" },
  { name: "Bangladesh", mapCode: "BD", currencyCode: "BDT" },
  { name: "Barbados", mapCode: "BB", currencyCode: "BBD" },
  { name: "Belarus", mapCode: "BY", currencyCode: "BYN" },
  { name: "Belize", mapCode: "BZ", currencyCode: "BZD" },
  { name: "Bhutan", mapCode: "BT", currencyCode: "BTN" },
  { name: "Bolivia", mapCode: "BO", currencyCode: "BOB" },
  { name: "Bosnia and Herzegovina", mapCode: "BA", currencyCode: "BAM" },
  { name: "Botswana", mapCode: "BW", currencyCode: "BWP" },
  { name: "Brazil", mapCode: "BR", currencyCode: "BRL" },
  { name: "Brunei", mapCode: "BN", currencyCode: "BND" },
  { name: "Bulgaria", mapCode: "BG", currencyCode: "BGN" },
  { name: "Burundi", mapCode: "BI", currencyCode: "BIF" },
  { name: "Cambodia", mapCode: "KH", currencyCode: "KHR" },
  { name: "Canada", mapCode: "CA", currencyCode: "CAD" },
  { name: "Cape Verde", mapCode: "CV", currencyCode: "CVE" },
  { name: "Chile", mapCode: "CL", currencyCode: "CLP" },
  { name: "China", mapCode: "CN", currencyCode: "CNY" },
  { name: "Colombia", mapCode: "CO", currencyCode: "COP" },
  { name: "Comoros", mapCode: "KM", currencyCode: "KMF" },
  { name: "Congo (Democratic Republic)", mapCode: "CD", currencyCode: "CDF" },
  { name: "Costa Rica", mapCode: "CR", currencyCode: "CRC" },
  { name: "Croatia", mapCode: "HR", currencyCode: "HRK" },
  { name: "Cuba", mapCode: "CU", currencyCode: "CUP" },
  { name: "Czech Republic", mapCode: "CZ", currencyCode: "CZK" },
  { name: "Denmark", mapCode: "DK", currencyCode: "DKK" },
  { name: "Djibouti", mapCode: "DJ", currencyCode: "DJF" },
  { name: "Dominican Republic", mapCode: "DO", currencyCode: "DOP" },
  {
    name: "East Caribbean Currency Union",
    mapCode: "XCD",
    currencyCode: "XCD",
  },
  { name: "Egypt", mapCode: "EG", currencyCode: "EGP" },
  { name: "El Salvador", mapCode: "SV", currencyCode: "USD" },
  { name: "Euro Area / Eurozone", mapCode: "EUR", currencyCode: "EUR" },
  { name: "Fiji", mapCode: "FJ", currencyCode: "FJD" },
  { name: "Gambia", mapCode: "GM", currencyCode: "GMD" },
  { name: "Georgia", mapCode: "GE", currencyCode: "GEL" },
  { name: "Ghana", mapCode: "GH", currencyCode: "GHS" },
  { name: "Guatemala", mapCode: "GT", currencyCode: "GTQ" },
  { name: "Guinea", mapCode: "GN", currencyCode: "GNF" },
  { name: "Honduras", mapCode: "HN", currencyCode: "HNL" },
  { name: "Hong Kong", mapCode: "HK", currencyCode: "HKD" },
  { name: "Hungary", mapCode: "HU", currencyCode: "HUF" },
  { name: "Iceland", mapCode: "IS", currencyCode: "ISK" },
  { name: "India", mapCode: "IN", currencyCode: "INR" },
  { name: "Indonesia", mapCode: "ID", currencyCode: "IDR" },
  { name: "Iran", mapCode: "IR", currencyCode: "IRR" },
  { name: "Iraq", mapCode: "IQ", currencyCode: "IQD" },
  { name: "Israel", mapCode: "IL", currencyCode: "ILS" },
  { name: "Jamaica", mapCode: "JM", currencyCode: "JMD" },
  { name: "Japan", mapCode: "JP", currencyCode: "JPY" },
  { name: "Jordan", mapCode: "JO", currencyCode: "JOD" },
  { name: "Kazakhstan", mapCode: "KZ", currencyCode: "KZT" },
  { name: "Kenya", mapCode: "KE", currencyCode: "KES" },
  { name: "Kuwait", mapCode: "KW", currencyCode: "KWD" },
  { name: "Kyrgyzstan", mapCode: "KG", currencyCode: "KGS" },
  { name: "Laos", mapCode: "LA", currencyCode: "LAK" },
  { name: "Lebanon", mapCode: "LB", currencyCode: "LBP" },
  { name: "Lesotho", mapCode: "LS", currencyCode: "LSL" },
  { name: "Liberia", mapCode: "LR", currencyCode: "LRD" },
  { name: "Libya", mapCode: "LY", currencyCode: "LYD" },
  { name: "Macau", mapCode: "MO", currencyCode: "MOP" },
  { name: "Madagascar", mapCode: "MG", currencyCode: "MGA" },
  { name: "Malawi", mapCode: "MW", currencyCode: "MWK" },
  { name: "Malaysia", mapCode: "MY", currencyCode: "MYR" },
  { name: "Maldives", mapCode: "MV", currencyCode: "MVR" },
  { name: "Mauritania", mapCode: "MR", currencyCode: "MRU" },
  { name: "Mauritius", mapCode: "MU", currencyCode: "MUR" },
  { name: "Mexico", mapCode: "MX", currencyCode: "MXN" },
  { name: "Moldova", mapCode: "MD", currencyCode: "MDL" },
  { name: "Mongolia", mapCode: "MN", currencyCode: "MNT" },
  { name: "Morocco", mapCode: "MA", currencyCode: "MAD" },
  { name: "Mozambique", mapCode: "MZ", currencyCode: "MZN" },
  { name: "Myanmar", mapCode: "MM", currencyCode: "MMK" },
  { name: "Namibia", mapCode: "NA", currencyCode: "NAD" },
  { name: "Nepal", mapCode: "NP", currencyCode: "NPR" },
  { name: "New Zealand", mapCode: "NZ", currencyCode: "NZD" },
  { name: "Nicaragua", mapCode: "NI", currencyCode: "NIO" },
  { name: "Nigerian Currency Zone", mapCode: "NG", currencyCode: "NGN" },
  { name: "North Korea", mapCode: "KP", currencyCode: "KPW" },
  { name: "Norway", mapCode: "NO", currencyCode: "NOK" },
  { name: "Oman", mapCode: "OM", currencyCode: "OMR" },
  { name: "Pakistan", mapCode: "PK", currencyCode: "PKR" },
  { name: "Panama", mapCode: "PA", currencyCode: "PAB" },
  { name: "Papua New Guinea", mapCode: "PG", currencyCode: "PGK" },
  { name: "Paraguay", mapCode: "PY", currencyCode: "PYG" },
  { name: "Peru", mapCode: "PE", currencyCode: "PEN" },
  { name: "Philippines", mapCode: "PH", currencyCode: "PHP" },
  { name: "Poland", mapCode: "PL", currencyCode: "PLN" },
  { name: "Qatar", mapCode: "QA", currencyCode: "QAR" },
  { name: "Romania", mapCode: "RO", currencyCode: "RON" },
  { name: "Russia", mapCode: "RU", currencyCode: "RUB" },
  { name: "Rwanda", mapCode: "RW", currencyCode: "RWF" },
  { name: "Saudi Arabia", mapCode: "SA", currencyCode: "SAR" },
  { name: "Serbia", mapCode: "RS", currencyCode: "RSD" },
  { name: "Seychelles", mapCode: "SC", currencyCode: "SCR" },
  { name: "Sierra Leone", mapCode: "SL", currencyCode: "SLL" },
  { name: "Singapore", mapCode: "SG", currencyCode: "SGD" },
  { name: "Solomon Islands", mapCode: "SB", currencyCode: "SBD" },
  { name: "Somalia", mapCode: "SO", currencyCode: "SOS" },
  { name: "South Africa", mapCode: "ZA", currencyCode: "ZAR" },
  { name: "South Korea", mapCode: "KR", currencyCode: "KRW" },
  { name: "South Sudan", mapCode: "SS", currencyCode: "SSP" },
  { name: "Sri Lanka", mapCode: "LK", currencyCode: "LKR" },
  { name: "Sudan", mapCode: "SD", currencyCode: "SDG" },
  { name: "Suriname", mapCode: "SR", currencyCode: "SRD" },
  { name: "Swaziland", mapCode: "SZ", currencyCode: "SZL" },
  { name: "Sweden", mapCode: "SE", currencyCode: "SEK" },
  { name: "Switzerland", mapCode: "CH", currencyCode: "CHF" },
  { name: "Syria", mapCode: "SY", currencyCode: "SYP" },
  { name: "Taiwan", mapCode: "TW", currencyCode: "TWD" },
  { name: "Tajikistan", mapCode: "TJ", currencyCode: "TJS" },
  { name: "Tanzania", mapCode: "TZ", currencyCode: "TZS" },
  { name: "Thailand", mapCode: "TH", currencyCode: "THB" },
  { name: "Tonga", mapCode: "TO", currencyCode: "TOP" },
  { name: "Trinidad and Tobago", mapCode: "TT", currencyCode: "TTD" },
  { name: "Tunisia", mapCode: "TN", currencyCode: "TND" },
  { name: "Turkey", mapCode: "TR", currencyCode: "TRY" },
  { name: "Turkmenistan", mapCode: "TM", currencyCode: "TMT" },
  { name: "Uganda", mapCode: "UG", currencyCode: "UGX" },
  { name: "Ukraine", mapCode: "UA", currencyCode: "UAH" },
  { name: "United Arab Emirates", mapCode: "AE", currencyCode: "AED" },
  { name: "United Kingdom", mapCode: "GB", currencyCode: "GBP" },
  { name: "United States", mapCode: "US", currencyCode: "USD" },
  { name: "Uruguay", mapCode: "UY", currencyCode: "UYU" },
  { name: "Uzbekistan", mapCode: "UZ", currencyCode: "UZS" },
  { name: "Vanuatu", mapCode: "VU", currencyCode: "VUV" },
  { name: "Venezuela", mapCode: "VE", currencyCode: "VES" },
  { name: "Vietnam", mapCode: "VN", currencyCode: "VND" },
  { name: "West African CFA Franc Zone", mapCode: "XOF", currencyCode: "XOF" },
  { name: "Yemen", mapCode: "YE", currencyCode: "YER" },
  { name: "Zambia", mapCode: "ZM", currencyCode: "ZMW" },
  { name: "Zimbabwe", mapCode: "ZW", currencyCode: "ZWL" },

  // Past
  { name: "Austro-Hungarian Empire", mapCode: "AH", currencyCode: "KUK" },
  {
    name: "Belgium-Luxembourg Economic Union",
    mapCode: "BLEU",
    currencyCode: "BLF",
  },
  { name: "Czechoslovakia", mapCode: "CS", currencyCode: "CSK" },
  { name: "East Germany", mapCode: "DD", currencyCode: "MDD" },
  { name: "German Empire", mapCode: "DE", currencyCode: "GEM" },
  { name: "Guinea-Bissau Currency Zone", mapCode: "GW", currencyCode: "GWP" },
  { name: "Kingdom of Hawaii", mapCode: "KH", currencyCode: "HWN" },
  { name: "Ottoman Empire", mapCode: "OE", currencyCode: "OTM" },
  { name: "Prussia", mapCode: "PR", currencyCode: "PRS" },
  { name: "Rhodesia", mapCode: "RH", currencyCode: "RHO" },
  { name: "Soviet Union", mapCode: "SU", currencyCode: "SUR" },
  { name: "Spanish Empire", mapCode: "SP", currencyCode: "ESP" },
  { name: "Unified Kingdom of Italy", mapCode: "IT", currencyCode: "ITL" },
  { name: "Weimar Republic", mapCode: "WR", currencyCode: "WRP" },
  { name: "West Germany", mapCode: "WG", currencyCode: "DEM" },
  { name: "Yugoslavia", mapCode: "YU", currencyCode: "YUD" },
  { name: "Zaire", mapCode: "ZR", currencyCode: "ZRN" },
];

export const photoPlaceholder =
  "https://t3.ftcdn.net/jpg/02/73/18/48/360_F_273184815_uOmhKYLSlx3hQWNsGciu1EfbKrf7g5bQ.jpg";
