name: Create Release on Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Extract Release Info from PR Title
      - name: Extract release info
        id: extract-release-info
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_BODY=${{ github.event.pull_request.body }}" >> $GITHUB_ENV

          # Extract version (e.g., "v1.2.0") from PR title
          version=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+')
          if [ -z "$version" ]; then
            echo "Release version not found in PR title!"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV

          # Default release name to PR title if not explicitly defined
          release_name="${{ github.event.pull_request.title }}"
          echo "release_name=$release_name" >> $GITHUB_ENV

      # Step 3: Get Release Notes from dev_pr_notes.md
      - name: Get release notes from dev_pr_notes.md
        id: release-notes
        run: |
          notes=$(cat dev_pr_notes.md)
          echo "notes=$notes" >> $GITHUB_ENV

      # Step 4: Create GitHub Release
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.release_name }}
          body: ${{ env.notes }}
          draft: false
          prerelease: false

      # Step 5: Reset dev_pr_notes.md
      - name: Reset dev_pr_notes.md
        run: |
          echo "" > dev_pr_notes.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dev_pr_notes.md
          git commit -m "Reset dev_pr_notes.md after release ${{ env.version }}"
          git push
