name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "PR merged."

      - name: Get release notes from dev_pr_notes.md
        id: release-notes
        if: github.event.pull_request.merged == true
        run: |
          notes=$(cat dev_pr_notes.md)
          echo "notes=$notes" >> $GITHUB_ENV

      - name: Create release
        if: github.event.pull_request.merged == true
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.event.pull_request.head.ref }}
          release_name: Release ${{ github.event.pull_request.head.ref }}
          body: ${{ env.notes }}
          draft: false
          prerelease: false
          generate_release_notes: false

      - name: Reset dev_pr_notes.md
        if: github.event.pull_request.merged == true
        run: |
          echo "" > dev_pr_notes.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dev_pr_notes.md
          git commit -m "Reset dev_pr_notes.md"
          git push
